# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetMoney' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LeanCloud'
  # Pods for GetMoney

  target 'GetMoneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetMoneyUITests' do
    # Pods for testing
  end

end
