# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GetMoney' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LeanCloud'
  pod 'SnapKit'
  pod 'SwiftyJSON', '~> 4.0' #JSON数据模型转换
  pod 'RxSwift’ #响应式编程RxSwift
  pod 'RxCocoa'#响应式编程RxSwift的拓展
  pod 'Moya' #基于Alamofire网络请求管理
  pod 'Kingfisher'
  
  # Pods for GetMoney

  target 'GetMoneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetMoneyUITests' do
    # Pods for testing
  end

end
